<?xml version="1.0"?>
<package format="3">
  <name>xmen_description</name>
  <version>1.0.0</version>
  <description>CCTV pan/tilt URDF and CAD meshes.</description>
  <maintainer email="hsmint.hong@gmail.com">hsmint</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
